### ISSUE TITLE
ConanCenter

### ISSUE THREAD

**Issue by mpusz** [martinmoene/observer-ptr-lite#6]
Could you please consider adding the package to ConanCenter?

**Comment by martinmoene** [comment]
Working on it...

**Comment by martinmoene** [comment]
@mpusz [PR submitted](https://github.com/conan-io/conan-center-index/pull/3232)

**Comment by mpusz** [comment]
Thanks!

**Comment by martinmoene** [comment]
@mpusz observer-ptr-lite is now available on conan center.

**Comment by mpusz** [comment]
Great! Thank you Martin :-)

**Comment by martinmoene** [comment]
You're welcome :_
